version: '3'
services:
  dash:
    build: 
      context: ./dash/
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - "./dash/data:/app/dash/data"
      - "./dash/app:/app/dash/app"
  mlapi:
    build:
      context: ./mlapi/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./mlapi/:/app/mlapi"
